spring.application.name=TaskManagement

spring.datasource.url=jdbc:postgresql://localhost:5432/taskdb
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.flyway.enabled=true

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
